# Tmux.conf
#
# Copyright 2001-2021 Verasonics, Inc.  All world-wide rights and remedies
# under all intellectual property laws and industrial property laws are
# reserved.  Verasonics Registered U.S. Patent and Trademark Office.

# must have tmux >2.9 installed

# mouse control
set -g mouse on

# loud or quiet?
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

# broadcast to all panels off/on
bind e set-window-option synchronize-panes

# turn off bottom status bar
set -g status off

# want to show secondary#, IP address
set -g base-index 1  
setw -g pane-base-index 1

set pane-border-status top
set -g pane-border-format "MultiSys Secondary #{pane_index} - 10.10.#{pane_index}.2"
