function BuildWithMcc(setUpScriptName, matFileName, varargin)
% BuildWithMcc  Create application with MATLAB Compiler
%   BuildWithMcc(setUpScriptName, matFileName) creates an executable
%   application using the script specified by setUpScript. The
%   variable matFileName must contain the name of the MAT file that is
%   generated by the SetUp script. The output will be named by stripping
%   "SetUp" from the SetUp script name. The executable will be contained
%   in a directory of the same name, in the Deploy subdirectory.
%
%   Example:
%   BuildWithMcc('SetUpL11_4vWideBeamHI', 'L11-4vWideBeamHI') creates
%   L11_4vWideBeamHI\Deploy\L11_4vWideBeamHI.exe

% Copyright (C) 2001-2024, Verasonics, Inc.
% All worldwide rights and remedies under all intellectual
% property laws and industrial property laws are reserved.

activate();
vpfRoot = fileparts(which('activate'));

if ~ispc
    error('%s only supports Windows.', mfilename)
end

if ~license('test', 'compiler')
    error('MATLAB Compiler must be installed to run %s', mfilename)
end

if ~isfile('System/licenseMgr.p')
    error(['Required file licenseMgr.p not found. Please copy ' ...
           'license.enc to the root directory, restart MATLAB, ' ...
           'and run activate.'])
end

extraMccArgs = {};
if nargin == 3
    extraMccArgs = varargin{1};
elseif nargin > 3
    error('Invalid number of input arguments');
end

% Remove file extension from input variables.
ext = '.m';
if endsWith(setUpScriptName, ext)
    setUpScriptName = setUpScriptName(1:end-length(ext));
end
ext = '.mat';
if endsWith(matFileName, ext)
    matFileName = matFileName(1:end-length(ext));
end

% Warn about removing output directory.
projectName = strrep(matFileName, '-', '_');
projectDir = ['./' projectName];
if isfolder(projectDir)
    warningState = warning();
    warning('off', 'backtrace')
    warning('Contents of the output directory "%s" will be deleted', ...
            projectName);
    warning(warningState);
end

% Run the SetUp script to output the mat file.
disp('Running SetUp script to create MAT file.');
disp('Clearing variables in the base workspace.');
if ~exist(setUpScriptName, 'file') % don't use isfile - it requires path to file
    error("The specified SetUp script '%s' was not found", ...
          setUpScriptName);
end
evalin('base', setUpScriptName);
matFilePath = fullfile('MatFiles', [matFileName '.mat']);
if ~isfile(matFilePath)
    error("The specified MAT file '%s' was not created by '%s'", ...
          matFileName, setUpScriptName);
end
evalin('base', 'clear all');

% Create directories for project files and compiler output.
% Note: Forward slashes are used for all mcc arguments, because it
% leads to more consistently formatted debug statements.
outputDir = [projectDir '/Deploy'];
if isfolder(projectDir)
    projectDirFullPath = fullfile(vpfRoot, projectDir);
    if isOnPath(projectDirFullPath)
        rmpath(projectDirFullPath);
    end
    outputDirFullPath = fullfile(vpfRoot, outputDir);
    if isOnPath(outputDirFullPath)
        rmpath(outputDirFullPath);
    end
    rmdir(projectDir, 's');
end
mkdir(projectDir);
mkdir(outputDir);

% Generate the callbacks and functions defined in SetUp file.
[~, fileName, fileExt] = fileparts(matFilePath);
initFilePath = [tempdir ['/' fileName '_InitOnly' fileExt]];
copyfile(matFilePath, initFilePath);
matFile = matfile(initFilePath);
Resource = matFile.Resource;
Resource = rmfield(Resource, 'DisplayWindow'); % Prevent showing display
Resource.Parameters.initializeOnly = 1;
Resource.Parameters.verbose = 0; % Suppress output
Resource.Parameters.simulateMode = 1; % Avoid "no probe detected" with hardware present
save(initFilePath, 'Resource', '-append');
UI = matFile.UI;
if isfield(UI, 'Statement')
    % Remove possible references to non-existent DisplayWindow
    UI = rmfield(UI, 'Statement');
    save(initFilePath, 'UI', '-append');
end
assignin('base', 'Mcr_GuiHide', 1); % Prevent showing GUI
assignin('base', 'vsTempDir', projectDir);
assignin('base', 'filename', initFilePath);
disp('Generating callbacks and external functions.');
evalin('base', 'VSX');
delete(initFilePath);

function writeline(fstring, varargin)
    fprintf(fid, sprintf('%s\n', fstring), varargin{:});
end

% Create launch script.
launchScript = [projectDir '/launch.m'];
fid = fopen(launchScript, 'w');
writeline("vpfRoot = activate();");
writeline("filename = '%s.mat';", matFileName);
writeline("vsTempDir = vpfRoot;");
writeline("try");
writeline("    VSX;");
writeline("catch ex");
writeline("    disp(getReport(ex));");
writeline("end");
writeline("com.verasonics.hal.hardware.Hardware.closeHardware();");
fclose(fid);

% Explicitly add p and m files at project root.
% Using a wildcard pattern (e.g. '-a ./*.m') reveals bug in R2019b:
% The warning "Your deployed application may error out ..." is issued if
% there is a startup.m file on the MATLAB path, even if that file
% is not included in your deployed application. See VTS-699 and Mathworks
% support case 02801896.
pFileArgs = createArgsArray('./*.p');
mFileArgs = createArgsArray('./*.m');

% Copy MAT file into project directory, which is included in build.
copyfile(matFilePath, projectDir);

fprintf(1, "Creating executable '%s'.\n", [projectName '.exe']);
mcc('-m', launchScript, ...
    '-R', ['-logfile,' projectName '.log'], ...
    '-o', projectName, ...
    '-d', outputDir, ...
    pFileArgs{:}, ...
    mFileArgs{:}, ...
    '-a', setUpScriptName, ...
    '-a', './Hal/lib', ... % TODO: Remove if VTS-668 is implemented
    '-a', './HwDiag/lib', ... % TODO: Remove if VTS-667 is implemented
    '-a', './System/*', ... % Exclude System/wd-install and System/app-install
    '-a', './System/+vsv', ...
    '-a', './System/P_Files', ...
    '-a', './System/Resource', ...
    '-a', './Tools', ...
    '-a', './Utilities', ...
    '-a', './vstoolbox', ...
    '-a', fullfile(toolboxdir('compiler'), 'mcrversion.m'), ... % runAcq has this dependency for deployed application
    '-a', projectDir, ...
    extraMccArgs{:})

close all;  % Close figures created during execution of mcc
% Clearing deletes temporary functions that need to exist while
% mcc is executing.
evalin('base', 'clear all');
end

function onPath = isOnPath(dir)
    pathCell = regexp(path(), pathsep, 'split');
    if ispc  % Windows is not case-sensitive
        onPath = any(strcmpi(dir, pathCell));
    else
        onPath = any(strcmp(dir, pathCell));
    end
end

function args = createArgsArray(filePattern, varargin)
    exclude = {};
    if nargin > 1
        exclude = varargin{1};
    end
    baseDir = fileparts(filePattern);
    files = dir(filePattern);
    args = {};
    j = 0;
    for i = 1:length(files)
        if any(contains(files(i).name, exclude))
            continue
        end
        j = j+1;
        args{2*j-1} = '-a'; %#ok<AGROW>
        args{2*j} = [baseDir '/' files(i).name]; %#ok<AGROW>
    end
end
